### ISSUE TITLE
missing installation and run instructions

### ISSUE THREAD

**Issue by gadieichhorn** [ahuggett26/Wind-farm-data#1]
Hi Andrew, 

I am Gadi from Pexapark.

Could you add instructions for:
* Local installation -> (npm install,...)
* How to run locally. (ng serve, ...)
* How to generate the data to view some charts

**Comment by ahuggett26** [comment]
Hi Gadi!

Thanks for your comments, I have added these instructions to the README.

Please let me know if there is anything else you'd like added!
